name = BDH Landing Page
description = Landing page for bowing down home.
preview = preview.png
template = bdh_landing_page

; Regions
regions[top-navigation] = Top Navigation
regions[branding]       = Branding
regions[content]        = Content
regions[prefooter]        = Pre-footer
regions[footer]         = Footer

; Stylesheets
;stylesheets[all][] = css/layouts/bdh_landing_page/bdh_landing_page.layout.css
;stylesheets[all][] = css/layouts/bdh_landing_page/bdh_landing_page.layout.no-query.css
